# Generated by Django 2.2.8 on 2020-03-22 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ecommerce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coreapi', '0002_auto_20200323_0036'),
        ('inventory', '0002_auto_20200323_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sellrecord_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellrecord',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sellrecord_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellrecord',
            name='ecommerce_has_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellrecord_ecommerce_has_product', to='Ecommerce.EcommerceHasProduct'),
        ),
        migrations.AddField(
            model_name='sellrecord',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sellrecord_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='Ecommerce',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partnership_company', to='coreapi.Company'),
        ),
        migrations.AddField(
            model_name='Ecommerce',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='partnership_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='Ecommerce',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partnership_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='Ecommerce',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partnership_partner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='Ecommerce',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partnership_product', to='inventory.Product'),
        ),
        migrations.AddField(
            model_name='Ecommerce',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='partnership_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ecommercesite',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ecommercesite_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ecommercesite',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ecommercesite_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ecommercesite',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ecommercesite_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ecommercehasproduct',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ecommercehasproduct_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ecommercehasproduct',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ecommercehasproduct_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ecommercehasproduct',
            name='ecommerce',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ecommercehasproduct_online_store', to='Ecommerce.EcommerceSite'),
        ),
        migrations.AddField(
            model_name='ecommercehasproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ecommercehasproduct_product', to='inventory.Product'),
        ),
        migrations.AddField(
            model_name='ecommercehasproduct',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ecommercehasproduct_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
