# Generated by Django 2.2.8 on 2020-01-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0002_partnership_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('sp', 'Super Admin'), ('ad', 'Admin'), ('us', 'User')], default='us', max_length=2),
        ),
    ]
