# Generated by Django 2.2.8 on 2020-04-12 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200323_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_sub_category', to='inventory.Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
